# Generated by Django 5.2 on 2025-04-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ristiseiska', '0002_season_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
