# Generated by Django 5.2 on 2025-05-01 12:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ristiseiska', '0004_game_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='date',
        ),
        migrations.AddField(
            model_name='game',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
